# 実行タイミング(手動実行)
on:
  workflow_dispatch:
    inputs:
#       param_name1:
#         description: 'param_name or description'
#         default: ''
#         required: true

# 名称
name: helloworld

# 実行ジョブ
jobs:
  greet:
    name: greeting
    runs-on: ubuntu-latest
    env:
      HELLO: 'Hello'

    steps:
      - name: say helloworld 01
        run: echo "helloworld."
        
      - name: say helloworld 02
        env:
          WORLD: 'World'
        run: echo "${{ env.HELLO }} ${{ env.WORLD }}."
